### ISSUE TITLE
NoneType is not iterable

### ISSUE THREAD

**Issue by WillBishop** [wchill/pySnap#15]
Wills-MacBook-Pro:pySnap Will$ python cli.py 
Please enter username: myusername
Please enter password: 
/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
https://feelinsonice-hrd.appspot.com/loq/login
{'username': 'myusername', 'timestamp': 1490351978050, 'password': 'mypass, 'req_token': 'token'}
{'User-Agent': 'Snapchat/7.1.0.10 (iPhone; iOS 8.1.1; gzip)'}
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>400 BAD_REQUEST</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: BAD_REQUEST</h1>
</body></html>

Traceback (most recent call last):
  File "cli.py", line 205, in <module>
    cli()
  File "cli.py", line 36, in cli
    if not s.login(username, password):
  File "/Users/Will/Desktop/pySnap/snapchat.py", line 181, in login
    if 'updates_response' not in result:
TypeError: argument of type 'NoneType' is not iterable

**Comment by wchill** [comment]
Snapchat has changed their API significantly since I last worked on this, so it's not surprising that it's not functional.
